# Release build
name: $(Year:yy).0.$(date:yy)$(DayOfYear)$(rev:.rr)

trigger: none
pr: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-2022'
  demands:
  - msbuild
  - visualstudio
  - vstest

stages:
- stage: Build
  jobs:
    - template: build.yml
      parameters:
        name: Release_Unicode_Win32
        configuration: Release Unicode
        platform: Win32
    - template: build.yml
      parameters:
        name: Release_Unicode_x64
        configuration: Release Unicode
        platform: x64

- stage: Release
  jobs:
    - template: release.yml
      parameters:
        name: signed
        sign: true
        title: MFCMAPI Month Year
        prerelease: false